### ISSUE TITLE
🚨 18.2.7 crashes, Ubuntu 24.04, both snap and AppImage

### ISSUE THREAD

**Issue by xenotropic** [super-productivity/super-productivity#7315]
### Version Used

18.2.7 crashes, Ubuntu 24.04, both snap and AppImage

### Expected Behavior

I thought this was maybe some error with my system but fails with seeming the same trace with two different packagings 

<img width="1591" height="502" alt="Image" src="https://github.com/user-attachments/assets/b0bc95b0-2ccb-46ff-b970-55db21e05be5" />

<img width="986" height="498" alt="Image" src="https://github.com/user-attachments/assets/5f66b6bd-cbc3-49d9-bad8-3cbad5cf9a9a" />

### Current Behavior

app crashes on latest release

### Steps to Reproduce

See screenshots; see my system info in #7298 

### Can you reproduce this reliably?

Yes, I can reproduce it reliably.

### Console Output

```shell
see screenshots
```

### documentation gap

- [ ] The documentation/[wiki](https://github.com/super-productivity/super-productivity/wiki) is unclear or incorrect for this case.
- [ ] There should be a note added to the documentation/[wiki](https://github.com/super-productivity/super-productivity/wiki) for this case.
- [ ] I can help improve the documentation.

**Comment by xenotropic** [comment]
18.2.5 works fine with both packagings

**Comment by kieric82** [comment]
Same situation on MacOS 26.4.1 ARM, installed version from homebrew. Works fine with 18.2.5. Thanks.

**Comment by LarsonPaul1** [comment]
Same issue, same OS and snap version. 

The **previous** issue that caused this program to not work on Ubuntu could be bypassed by running `superproductivity --ozone-platform=x11`. However, this newest problem, introduced between 18.2.5 and 18.2.7, causes an entirely new issue. 

Pasting my console output for searchability and ease of copying:

```
~$ superproductivity
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '../src/app/util/get-backup-timestamp'
Require stack:
- /snap/superproductivity/3501/resources/app.asar/electron/backup.js
- /snap/superproductivity/3501/resources/app.asar/electron/ipc-handlers/app-data.js
- /snap/superproductivity/3501/resources/app.asar/electron/ipc-handlers/index.js
- /snap/superproductivity/3501/resources/app.asar/electron/ipc-handler.js
- /snap/superproductivity/3501/resources/app.asar/electron/start-app.js
- /snap/superproductivity/3501/resources/app.asar/electron/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1463:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:140033)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1073:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1078:22)
    at Module._load (node:internal/modules/cjs/loader:1249:25)
    at c._load (node:electron/js2c/node_init:2:18047)
    at wrapModuleLoad (node:internal/modules/cjs/loader:262:19)
    at Module.require (node:internal/modules/cjs/loader:1563:12)
    at require (node:internal/modules/helpers:152:16)
    at Object.<anonymous> (/snap/superproductivity/3501/resources/app.asar/electron/backup.js:43:32)
```

**Comment by Gitoffthelawn** [comment]
Same crash due to uncaught exception with v18.2.7 in Windows 11:
```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Cannot find module '../src/app/util/get-backup-timestamp'
Require stack:
- ..\super-productivity\18.2.7\resources\app.asar\electron\backup.js
- ..\super-productivity\18.2.7\resources\app.asar\electron\ipc-handlers\app-data.js
- ..\super-productivity\18.2.7\resources\app.asar\electron\ipc-handlers\index.js
- ..\super-productivity\18.2.7\resources\app.asar\electron\ipc-handler.js
- ..\super-productivity\18.2.7\resources\app.asar\electron\start-app.js
- ..\super-productivity\18.2.7\resources\app.asar\electron\main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1463:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:140033)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1073:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1078:22)
    at Module._load (node:internal/modules/cjs/loader:1249:25)
    at c._load (node:electron/js2c/node_init:2:18047)
    at wrapModuleLoad (node:internal/modules/cjs/loader:262:19)
    at Module.require (node:internal/modules/cjs/loader:1563:12)
    at require (node:internal/modules/helpers:152:16)
    at Object.<anonymous> (..\super-productivity\18.2.7\resources\app.asar\electron\backup.js:43:32)
```

**Comment by itormint** [comment]
Hi!! I have the same issue on Manjaro using appimage version 18.2.7:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '../src/app/util/get-backup-timestamp'
Require stack:
- /opt/Super Productivity/resources/app.asar/electron/backup.js
- /opt/Super Productivity/resources/app.asar/electron/ipc-handlers/app-data.js
- /opt/Super Productivity/resources/app.asar/electron/ipc-handlers/index.js
- /opt/Super Productivity/resources/app.asar/electron/ipc-handler.js
- /opt/Super Productivity/resources/app.asar/electron/start-app.js
- /opt/Super Productivity/resources/app.asar/electron/main.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:1463:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:140033)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1073:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1078:22)
    at Module._load (node:internal/modules/cjs/loader:1249:25)
    at c._load (node:electron/js2c/node_init:2:18047)
    at wrapModuleLoad (node:internal/modules/cjs/loader:262:19)
    at Module.require (node:internal/modules/cjs/loader:1563:12)
    at require (node:internal/modules/helpers:152:16)
    at Object.<anonymous> (/opt/Super Productivity/resources/app.asar/electron/backup.js:43:32)
```

**Comment by MFykoopS** [comment]
Exact same error here on Ubuntu 24.04, only since updating to 18.2.7 via Snap (had to use the `--ozone-platform=x11` workaround before the update). I'm not posting my log because it is identical to those of the other posters.

**Comment by gwthmsb** [comment]
Environment:

OS: Ubuntu 24.04
Install methods tested: Snap and .deb
Snap revision: 3501 (broken)
.deb version: 18.2.7

Issue:
The application crashes immediately on startup with the same error(mentioned above) for both Snap and .deb installations.

**Comment by Patrick-TS** [comment]
Same here with Win10, 18.2.5 worked fine but lost tray icon.

<img width="558" height="493" alt="Image" src="https://github.com/user-attachments/assets/2027f30d-fcb8-439c-b9b6-a71bb327daca" />

**Comment by xenotropic** [comment]
fixed in 18.2.8

**Comment by johannesjo** [comment]
Thank you very much! And sorry for the inconvenience!

**Comment by Patrick-TS** [comment]
The application works! However, the tray icon still losts. Which is important, when I turn on the the "Minimize to the tray" I find no way to show the window again without the tray icon or hot key.

**Comment by xenotropic** [comment]
@Patrick-TS re: icon in tray see #7298 if about linux, see #7282 about Windows (if you're on a mac that might actually be a new issue)
